### ISSUE TITLE
SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by rbocobo** [rednez/angular-user-idle#1] opened 2017-10-10 16:32 UTC
getting a "SyntaxError: Unexpected token <" error when importing module

still getting the error after adding the following in package.config.ts:

let angular_user_idle: ExtendPackages[] = [{ 
      name: 'angular-user-idle', 
      path: 'node_modules/angular-user-idle/user-idle.umd.js' 
    }];   

let additionalPackages: ExtendPackages[] = [

      ...lodash,
      ...angular_user_idle
    ];

    this.addPackagesBundles(additionalPackages);

**Comment by rednez** [comment] 2017-10-10 18:53
@rbocobo Please specify bundler are you using. I'll try to reproduce that problem.

**Comment by rbocobo** [comment] 2017-10-10 23:44
SystemJS

**Comment by rednez** [comment] 2017-10-11 09:02
I tested library with Webpack and Rollup (by [angular-seed](https://github.com/mgechev/angular-seed)) and all work fine.
Unfortunately I closing your issue because you don't provided details about your config of your project and bundler you used.

**Closed by rednez** 2017-10-11 09:02 UTC
